[package]
name = "folder_favorite"
version = "1.3.3"
edition = "2021"

[dependencies]
arboard = "3.2.0"
clap = {version = "4.0.32", features= ["derive"]} 
directories = "4.0.1"
colored = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.0.0"

